### ISSUE TITLE
Feature request: "Skip all" for "Resolve IPs"

### ISSUE THREAD

**Issue by mdenzel** [cgosec/Blauhaunt#3]
Hello,

when resolving IPs with the "Resolve IPs" button, one gets pop ups if multiple IPs match to the same system-name. For dynamic IPs this can be a lot.

A "Skip all" button would be helpful.

**Comment by cgosec** [comment]
There is a "Cancle" button now in the modal. When clicked all the remaining resolve modals will be skipped. Already applied mappings are set
