### ISSUE TITLE
Interaction with Velo Hunts does not check if the hunt is related to Blauhaunt

### ISSUE THREAD

**Issue by Matthijsy** [cgosec/Blauhaunt#6]
I am just trying out Blauhaunt and experience some issues. When clicking the "Load Root" button the logic in `veloAPI.js` tries to fetch data from the server. However, this logic does interfere with hunts that are not related to Blauhaunt. I now have a "BLAUHAUNT" cell in every hunt, even if it does not load data for blauhaunt. Furthermore the reload logic fails on this line https://github.com/cgosec/Blauhaunt/blob/main/app/static/js/veloAPI.js#L136 since the data object is empty.

Am I doing something wrong, or is this a bug in Blauhaunt?

**Comment by cgosec** [comment]
Hi, thank you for creating the issue. This is likely a bug of blauhaunt. The Velo integration was only tested in a small lab so far. I will check the code later based on your description

**Comment by cgosec** [comment]
The bug when no Blauhaunt Hunt is running should be solved.
The data object is checked now too.

Please let me know if it works now.

**Comment by Matthijsy** [comment]
Great, it indeeds looks to work now
