### ISSUE TITLE
Velociraptor Blauhaunt Integration: veloAPI changedorg moved

### ISSUE THREAD

**Issue by WickedJack99** [cgosec/Blauhaunt#8]
Yo ✌️, I think Velociraptor' API got updated, since the property org is not available at data.interface_traits.

See: https://github.com/cgosec/Blauhaunt/blob/main/app/static/js/veloAPI.js Line 393

My project is fetching the latest version of Velo and if I move to .../api/v1/GetUserUITraits I see:

![image](https://github.com/user-attachments/assets/66aa2c34-6e31-469a-9335-4636d59e2498)

I think it would be best to use "data.orgs" or something like that.

Could you change this, so it works with the newest version of the API? 😊

Also found a small typo at 395, "console.log("No or**d**ID available. Running in standalone mode... may you try to select an organization.");" should be g I guess.

**Comment by cgosec** [comment]
Hi, sorry for the very long time to answer!

updated to the new API version and did a small Lab test.

Please open a new issue if not solved,
